// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK6sbzU3RleWpmizDiMwAXEH4kAz2harU',
    appId: '1:298921749516:web:b3b9db239f9988384d1229',
    messagingSenderId: '298921749516',
    projectId: 'flutter-project-5a21d',
    authDomain: 'flutter-project-5a21d.firebaseapp.com',
    storageBucket: 'flutter-project-5a21d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrTr-XBRgTTaUV-iyvLhcOfn1Zhlh-ew',
    appId: '1:298921749516:android:fb75d7e5b1ccbee84d1229',
    messagingSenderId: '298921749516',
    projectId: 'flutter-project-5a21d',
    storageBucket: 'flutter-project-5a21d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7U-WS0D9r_OeadbkJCEFxaKCwFyCz7c',
    appId: '1:298921749516:ios:3e066fa3d7aa1d704d1229',
    messagingSenderId: '298921749516',
    projectId: 'flutter-project-5a21d',
    storageBucket: 'flutter-project-5a21d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7U-WS0D9r_OeadbkJCEFxaKCwFyCz7c',
    appId: '1:298921749516:ios:a293df08852544c24d1229',
    messagingSenderId: '298921749516',
    projectId: 'flutter-project-5a21d',
    storageBucket: 'flutter-project-5a21d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
